FROM node:22-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS build
ARG DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gickvpn?schema=public
ARG JWT_SECRET
ARG ADMIN_EMAILS
ARG ADMIN_INITIAL_PASSWORD
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_TELEGRAM_BOT_USERNAME
ARG TELEGRAM_BOT_TOKEN
ARG REMNAWAVE_BASE_URL
ARG REMNAWAVE_API_TOKEN
ARG YOOKASSA_SHOP_ID
ARG YOOKASSA_SECRET_KEY
ARG YOOKASSA_WEBHOOK_SECRET
ARG YOOKASSA_ALLOWED_IPS
ARG PLATEGA_API_KEY
ARG PLATEGA_MERCHANT_ID
ARG PLATEGA_WEBHOOK_SECRET
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SECURE
ARG SMTP_USER
ARG SMTP_PASS
ARG EMAIL_FROM
ARG REFERRAL_REWARD_TYPE
ARG REFERRAL_REWARD_VALUE
ARG CRON_SECRET
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV ADMIN_EMAILS=${ADMIN_EMAILS}
ENV ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
ENV NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=${NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV REMNAWAVE_BASE_URL=${REMNAWAVE_BASE_URL}
ENV REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
ENV YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
ENV YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
ENV YOOKASSA_WEBHOOK_SECRET=${YOOKASSA_WEBHOOK_SECRET}
ENV YOOKASSA_ALLOWED_IPS=${YOOKASSA_ALLOWED_IPS}
ENV PLATEGA_API_KEY=${PLATEGA_API_KEY}
ENV PLATEGA_MERCHANT_ID=${PLATEGA_MERCHANT_ID}
ENV PLATEGA_WEBHOOK_SECRET=${PLATEGA_WEBHOOK_SECRET}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_SECURE=${SMTP_SECURE}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_PASS=${SMTP_PASS}
ENV EMAIL_FROM=${EMAIL_FROM}
ENV REFERRAL_REWARD_TYPE=${REFERRAL_REWARD_TYPE}
ENV REFERRAL_REWARD_VALUE=${REFERRAL_REWARD_VALUE}
ENV CRON_SECRET=${CRON_SECRET}
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public
RUN npx prisma generate
RUN npm run build

FROM base AS tools
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run db:seed"]

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
RUN apk add --no-cache libc6-compat openssl && addgroup -S nodejs && adduser -S nextjs -G nodejs
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/.next-local/standalone ./
COPY --from=build /app/.next-local/static ./.next-local/static
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/prisma.config.ts ./prisma.config.ts
COPY --from=build /app/scripts/worker.mjs ./scripts/worker.mjs
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
